{% set version = "1.0.1" %}

package:
  name: emperor
  version: {{ version }}

source:
  fn: emperor-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/e/emperor/emperor-{{ version }}.tar.gz
  sha256: e4d30501d079bfe50c3e015f83ac741d60474296859b470d500cfcd8a2571fc7

build:
  number: 1
  skip: true  # [win]
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - scipy >=0.17.0
    - future
    - jinja2
    - scikit-bio >=0.4.1,<0.5.0  # [py2k]
    - scikit-bio >=0.4.1  # [py3k]
    - numpy >=1.7
    - pandas
    - click
    - setuptools
    - pip

  run:
    - python
    - scipy >=0.17.0
    - future
    - jinja2
    - scikit-bio >=0.4.1,<0.5.0  # [py2k]
    - scikit-bio >=0.4.1  # [py3k]
    - numpy >=1.7
    - pandas
    - click
    - setuptools

test:
  imports:
    - emperor  # [ not (linux and py2k)]
    - emperor.qiime_backports  # [ not (linux and py2k)]

about:
  home: http://emperor.microbio.me
  license: BSD 3-Clause
  license_file: LICENSE.md
  summary: Emperor a tool for the analysis and visualization of large microbial ecology datasets

extra:
  recipe-maintainers:
    - ElDeveloper
