{% set version = "1.0.4" %}

package:
  name: emperor
  version: {{ version }}

source:
  fn: emperor-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/e/emperor/emperor-{{ version }}.tar.gz
  sha256: 8b57d6ee3709b62b4dfdd8e1f815dd88e5fee3a05947d72fa32191a16ac08854

build:
  number: 2
  skip: true  # [win]
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  host:
    - python
    - scipy >=0.17.0
    - future
    - jinja2
    - scikit-bio
    - numpy >=1.7
    - pandas
    - click
    - setuptools
    - pip

  run:
    - python
    - scipy >=0.17.0
    - future
    - jinja2
    - scikit-bio
    - numpy >=1.7
    - pandas
    - click
    - setuptools

test:
  imports:
    - emperor  # [ not (linux and py2k)]
    - emperor.qiime_backports  # [ not (linux and py2k)]

about:
  home: http://emperor.microbio.me
  license: BSD 3-Clause
  license_file: LICENSE.md
  summary: Emperor a tool for the analysis and visualization of large microbial ecology datasets

extra:
  recipe-maintainers:
    - ElDeveloper
